### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by dimqua** [vadrian89/cumulus-qt#41]
I think it'd nice to add this app to the F-Droid repository. I already opened a request [here](https://gitlab.com/fdroid/rfp/issues/744). Don't you mind?

**Comment by vadrian89** [comment]
Hello, thanks for the interest. I don't have any problems about the application being made available on F-Droid repository, though I need to mention a few things because the application has some issues which I haven't tackled.  
On Android Pie, so far, I encountered some issues:    
- when the view for searching locations is opened, the location-based search on the bottom isn't finding anything;
- sometimes the saved locations list won't appear;   
- sometimes the application will just start frozen;
- sometimes it will suddenly crash;   
- on the first run I get an AppCompat error, but after I push OK button nothing happens and the app still runs, so there's that;

On the features side there are some things I need to address, which I haven't the moment I am writing this:   
- the comboboxes for selections have the font to big;
- the UI doesn't show people need to slide to see the locations list and unless a person properly looked at the screenshots at first launch they will be confused where to go to  add/change locations;
- Yahoo provider isn't working at the moment because issue: https://github.com/vadrian89/cumulus-qt/issues/40;
- there is no option to add a person's own api key for OpenWeatherMap and Wunderground providers at this moment, so if there are to many users they servers refreshing at the sametime(doughtful) will return nothing;
- the application is not translated. The menu is in english, while the weather provided is based of regional settings of the device if it's available;

For description you could put the following:  
Cross platform and open source weather application for GNU/Linux and Android built with Qt.
Features:  
- multiple weather providers: OpenWeatherMap & Weather Underground   
- current weather and forecast    
- custom color background  
- locations list

I haven't managed to get some work on it, lately, because I am in the middle of a big project which is important for my future career and between that and work time I have little time to spare so that's why I haven't added any updates to the application. 
On a side note I am also working on developing a custom QML UI kit for my current and future Qt applications and I want the new features to use my custom kit.

So if you think the issues will not be a huge bother I am ok with it.
You could mention in the description that the application is a work in progress(or something), if you feel you need it.

**Comment by IzzySoft** [comment]
@vadrian89 as for the description, you could establish [Fastlane file structure](https://gitlab.com/snippets/1895688) in your repo (that way you can maintain it yourself and also include screenshots).

Hope your big project was a success! What are the chances (and ETA) to get Fastlane in and a new release out? The RFP already hangs idle for a year now – so if you say you can get on that within a couple of weeks, we'd better wait for that and get it launched straight, instead of starting with a version that's two and a half years old :wink:

**Comment by vadrian89** [comment]
> @vadrian89 as for the description, you could establish [Fastlane file structure](https://gitlab.com/snippets/1895688) in your repo (that way you can maintain it yourself and also include screenshots).
> 
> Hope your big project was a success! What are the chances (and ETA) to get Fastlane in and a new release out? The RFP already hangs idle for a year now – so if you say you can get on that within a couple of weeks, we'd better wait for that and get it launched straight, instead of starting with a version that's two and a half years old 😉

Wow, can't believe it's been over an year, how time flew. The project takes shapes slowly, sadly, even worsened a bit due to the Covid-19 outbreak......

Managed to start my own B2B software development company but it seems managing it takes a big chunk of my time and the only time I do development is for client needs and none for spare projects...

When I will manage to build a team which can free my time, then, I will pursue improving the application. In the meantime I cannot find the time to spare, especially now when the economy drops and more and more business suspend/shutdown due to this virus.

My apologies for wasting your time.

**Comment by IzzySoft** [comment]
No worries, all fine. I might send you a heads-up every few months or so (whenever I'm triaging open issues). Having enough work to do usually is a good sign that one can make a living – so all the best for your new company! And don't feel pressed by my reminders, rather count them as "he didn't forget me" :smile:

Looking forward to your team being established :crossed_fingers:

**Comment by vadrian89** [comment]
Thank you, stay healthy!

**Comment by IzzySoft** [comment]
I hope you're fine still! And I'll send that [RFP at F-Droid](https://gitlab.com/fdroid/rfp/-/issues/744) to sleep now (closing the issue). It doesn't seem likely you'll have anything ready for release in near time (no offense meant). Please give us a ping should you revive your project.

**Comment by vadrian89** [comment]
> I hope you're fine still! And I'll send that [RFP at F-Droid](https://gitlab.com/fdroid/rfp/-/issues/744) to sleep now (closing the issue). It doesn't seem likely you'll have anything ready for release in near time (no offense meant). Please give us a ping should you revive your project.

Helo, I am fine, health-wise.
You should do that as I don't plan to pick up the project again for the moment, can't believe almost a year passed since our last talk.
I haven't managed to do much with the whole Covid 19, just get more in debt to stay alive :D.
On top of that I've changed technologies used for app development, from Qt to Flutter, so it would be a waste of time for me to get up-to-date with Qt at the moment as my schedule is pretty full already.
If I will re-write the app in Flutter, will let you know, in the meantime you should treat it as abandoned.

And don't worry, I don't get offended by the truth. :)

**Comment by IzzySoft** [comment]
Thanks a lot for your answer! Yes, given the license situation around Qt, switching to "something else" definitely isn't the worst idea :laughing:

All the best for you personally (wishing for a time where "Corona" is just a beer, "positive" is something good, "tests" are reserved for software, "isolation" is something for electricity & thermos, and "Donald" is just a duck – stay healthy!) And be welcome with any of your FOSS Android projects to get in touch with us again!
